"""empty message

Revision ID: a19c06e53091
Revises: 
Create Date: 2023-02-26 21:46:45.883385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a19c06e53091'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user_accounts',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user_accounts.username'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('items',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('lifespan', sa.SmallInteger(), nullable=True),
    sa.Column('general_name', sa.String(), nullable=False),
    sa.Column('consumable_peripheral', sa.Boolean(), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('assigned_user', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('users_locations',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('users_id', sa.SmallInteger(), nullable=False),
    sa.Column('locations_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['locations_name'], ['locations.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_locations')
    op.drop_table('items')
    op.drop_table('users')
    op.drop_table('user_accounts')
    op.drop_table('locations')
    # ### end Alembic commands ###
